export default class DataSamples {
    static euData = {
        fs_id: '2041935',
        change_date: '2022-01-17T10:56:41Z',
        url: '/Games/Nintendo-Switch-download-software/-METAL-SLUG-1st-2nd-MISSION-Double-Pack-2041935.html',
        type: 'GAME',
        dates_released_dts: ['2021-09-15T00:00:00Z'],
        club_nintendo: false,
        pretty_date_s: '15/09/2021',
        play_mode_tv_mode_b: true,
        play_mode_handheld_mode_b: true,
        product_code_txt: ['HACPAZPWA'],
        image_url_sq_s: 'https://fs-prod-cdn.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_MetalSlug1stAnd2ndMissionDoublePack_image500w.jpg',
        deprioritise_b: false,
        pg_s: 'GAME',
        compatible_controller: ['nintendoswitch_pro_controller'],
        image_url: 'https://fs-prod-cdn.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_MetalSlug1stAnd2ndMissionDoublePack_image500w.jpg',
        originally_for_t: 'HAC',
        cloud_saves_b: true,
        priority: '2031-09-15T15:00:00Z',
        digital_version_b: true,
        title_extras_txt: ['"METAL SLUG 1st & 2nd MISSION" Double Pack'],
        image_url_h2x1_s: 'https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_download_software_1/H2x1_NSwitchDS_MetalSlug1stAnd2ndMissionDoublePack_image500w.jpg',
        system_type: ['nintendoswitch_downloadsoftware'],
        age_rating_sorting_i: 12,
        game_categories_txt: ['action', 'shooter'],
        play_mode_tabletop_mode_b: true,
        publisher: 'SNK',
        product_code_ss: ['HACPAZPWA'],
        excerpt: 'From the hit action series METAL SLUG comes two popular titles on the NGPC for you to enjoy! Jump into battle and complete all the missions!',
        nsuid_txt: ['70010000034009'],
        date_from: '2021-09-15T00:00:00Z',
        language_availability: ['english,japanese'],
        price_has_discount_b: false,
        product_catalog_description_s: 'From the hit action series METAL SLUG comes two popular titles on the NGPC for you to enjoy! Jump into battle and complete all the missions!',
        price_discount_percentage_f: 0,
        title: '"METAL SLUG 1st & 2nd MISSION" Double Pack',
        sorting_title: '"METAL SLUG 1st & 2nd MISSION" Double Pack',
        copyright_s: '©SNK CORPORATION ALL RIGHTS RESERVED.',
        wishlist_email_square_image_url_s: 'https://fs-prod-cdn.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_MetalSlug1stAnd2ndMissionDoublePack_square_image_wishlist.jpg',
        players_to: 1,
        wishlist_email_banner640w_image_url_s: 'https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_download_software_1/H2x1_NSwitchDS_MetalSlug1stAnd2ndMissionDoublePack_banner_image_wishlist_640w.jpg',
        playable_on_txt: ['HAC'],
        hits_i: 300,
        pretty_game_categories_txt: ['Action', 'Shooter'],
        switch_game_voucher_b: false,
        game_category: ['action,shooter'],
        system_names_txt: ['Nintendo Switch'],
        pretty_agerating_s: 'PEGI 12',
        price_regular_f: 13.49,
        eshop_removed_b: false,
        age_rating_type: 'pegi',
        price_sorting_f: 13.49,
        price_lowest_f: 13.49,
        age_rating_value: '12',
        physical_version_b: false,
        wishlist_email_banner460w_image_url_s: 'https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_download_software_1/H2x1_NSwitchDS_MetalSlug1stAnd2ndMissionDoublePack_banner_image_wishlist_460w.jpg',
        _version_: 1735624225142603800
    }

    static jpData = {
        InitialCode: "HACAACAA",
        TitleName: "魔界戦記ディスガイア5",
        MakerName: "日本一ソフトウェア",
        MakerKana: "",
        Price: "7, 538円(税込)",
        SalesDate: "2017.3.3",
        SoftType: "pkg_dl",
        PlatformID: 2002,
        DlIconFlg: 1,
        LinkURL: "/titles/70010000000148",
        ScreenshotImgFlg: 1,
        ScreenshotImgURL: "https://img-eshop.cdn.nintendo.net/i/1c34e431fa5d1b1198515e22e1beafe45b9050b5b5b28403f15cd315af0944f7.jpg"
    }

    // { "InitialCode": "HACAACCA", "TitleName": "1-2-Switch（ワンツースイッチ）", "MakerName": "任天堂", "MakerKana": "", "Price": "5,478円(税込)", "SalesDate": "2017.3.3", "SoftType": "pkg_dl", "PlatformID": 2002, "DlIconFlg": 1, "LinkURL": "/titles/70010000000027", "ScreenshotImgFlg": 1, "ScreenshotImgURL": "https://img-eshop.cdn.nintendo.net/i/e7bf6bed37524768227f19604731582136168a5411e049d5ef094afd9de7a13f.jpg" }
    // {"fs_id":"1969948","change_date":"2022-01-17T10:56:29Z","url":"/Games/Nintendo-Switch-download-software/0-Degrees-1969948.html","type":"GAME","dates_released_dts":["2021-05-19T00:00:00Z"],"club_nintendo":false,"pretty_date_s":"19/05/2021","play_mode_tv_mode_b":true,"play_mode_handheld_mode_b":true,"product_code_txt":["HACPA3WCA"],"image_url_sq_s":"https://fs-prod-cdn.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_0Degrees_image500w.jpg","deprioritise_b":false,"pg_s":"GAME","compatible_controller":["nintendoswitch_pro_controller"],"image_url":"https://fs-prod-cdn.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_0Degrees_image500w.jpg","originally_for_t":"HAC","cloud_saves_b":true,"priority":"2031-05-18T22:00:00Z","digital_version_b":true,"title_extras_txt":["0 Degrees"],"image_url_h2x1_s":"https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_download_software_1/H2x1_NSwitchDS_0Degrees_image500w.jpg","system_type":["nintendoswitch_downloadsoftware"],"age_rating_sorting_i":3,"game_categories_txt":["action","platformer","puzzle"],"play_mode_tabletop_mode_b":true,"publisher":"eastasiasoft","product_code_ss":["HACPA3WCA"],"excerpt":"Warp your way through a wintry platforming adventure!","nsuid_txt":["70010000039476"],"date_from":"2021-05-19T00:00:00Z","language_availability":["english"],"price_has_discount_b":false,"product_catalog_description_s":"Warp your way through a wintry platforming adventure!","price_discount_percentage_f":0,"title":"0 Degrees","sorting_title":"0 Degrees","copyright_s":"© Eastasiasoft Limited, Nerd Games, Kiddo Dev. All Rights Reserved.","wishlist_email_square_image_url_s":"https://fs-prod-cdn.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_0Degrees_square_image_wishlist.jpg","players_to":1,"wishlist_email_banner640w_image_url_s":"https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_download_software_1/H2x1_NSwitchDS_0Degrees_banner_image_wishlist_640w.jpg","playable_on_txt":["HAC"],"hits_i":300,"pretty_game_categories_txt":["Action","Platformer","Puzzle"],"switch_game_voucher_b":false,"game_category":["action,platformer,puzzle"],"system_names_txt":["Nintendo Switch"],"pretty_agerating_s":"PEGI 3","price_regular_f":4.49,"eshop_removed_b":false,"age_rating_type":"pegi","price_sorting_f":4.49,"price_lowest_f":4.49,"age_rating_value":"3","physical_version_b":false,"wishlist_email_banner460w_image_url_s":"https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_download_software_1/H2x1_NSwitchDS_0Degrees_banner_image_wishlist_460w.jpg","_version_":1737707959117414400},{"fs_id":"1173186","change_date":"2022-01-17T10:55:03Z","url":"/Games/Nintendo-Switch-games/1-2-Switch-1173186.html","type":"GAME","dates_released_dts":["2017-03-03T00:00:00Z"],"club_nintendo":false,"hd_rumble_b":true,"multiplayer_mode":"simultaneous","pretty_date_s":"03/03/2017","play_mode_tv_mode_b":true,"play_mode_handheld_mode_b":true,"product_code_txt":["HACPAACCA"],"image_url_sq_s":"https://fs-prod-cdn.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_5/SQ_NSwitch_12Switch_image500w.jpg","deprioritise_b":false,"pg_s":"GAME","image_url":"https://fs-prod-cdn.nintendo-europe.com/media/images/05_packshots/games_13/nintendo_switch_8/PS_NSwitch_12Switch_PEGI_image500w.jpg","originally_for_t":"HAC","paid_subscription_required_b":false,"cloud_saves_b":false,"priority":"2027-03-03T13:45:00Z","digital_version_b":false,"title_extras_txt":["1-2-Switch"],"image_url_h2x1_s":"https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_12Switch_image500w.jpg","system_type":["nintendoswitch_gamecard,nintendoswitch_digitaldistribution"],"age_rating_sorting_i":7,"game_categories_txt":["party"],"play_mode_tabletop_mode_b":true,"publisher":"Nintendo","ir_motion_camera_b":true,"product_code_ss":["HACPAACCA"],"excerpt":"Lock eyes with your opponent and get ready to discover the many functions of the Joy-Con in 1-2-Switch for Nintendo Switch!","nsuid_txt":["70010000000024"],"date_from":"2017-03-03T00:00:00Z","language_availability":["dutch,english,french,german,italian,russian,spanish"],"price_has_discount_b":false,"product_catalog_description_s":"Lock eyes with your opponent and get ready to discover the many functions of the Joy-Con in 1-2-Switch for Nintendo Switch!","price_discount_percentage_f":0,"title":"1-2-Switch","sorting_title":"1-2-Switch","copyright_s":"© 2017 Nintendo ","wishlist_email_square_image_url_s":"https://fs-prod-cdn.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_5/SQ_NSwitch_12Switch_square_image_wishlist.jpg","players_to":2,"wishlist_email_banner640w_image_url_s":"https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_12Switch_banner_image_wishlist_640w.jpg","voice_chat_b":false,"playable_on_txt":["HAC"],"hits_i":1,"pretty_game_categories_txt":["Party"],"switch_game_voucher_b":true,"game_category":["party"],"system_names_txt":["Nintendo Switch"],"pretty_agerating_s":"PEGI 7","price_regular_f":39.99,"eshop_removed_b":false,"players_from":1,"age_rating_type":"pegi","price_sorting_f":39.99,"price_lowest_f":39.99,"age_rating_value":"7","physical_version_b":true,"wishlist_email_banner460w_image_url_s":"https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_12Switch_banner_image_wishlist_460w.jpg","_version_":1737798552449450000},
}