export default class DataSamples {
    static euGameData = {
        fs_id: '2041935',
        change_date: '2022-01-17T10:56:41Z',
        url: '/Games/Nintendo-Switch-download-software/-METAL-SLUG-1st-2nd-MISSION-Double-Pack-2041935.html',
        type: 'GAME',
        dates_released_dts: ['2021-09-15T00:00:00Z'],
        club_nintendo: false,
        pretty_date_s: '15/09/2021',
        play_mode_tv_mode_b: true,
        play_mode_handheld_mode_b: true,
        product_code_txt: ['HACPAZPWA'],
        image_url_sq_s: 'https://fs-prod-cdn.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_MetalSlug1stAnd2ndMissionDoublePack_image500w.jpg',
        deprioritise_b: false,
        pg_s: 'GAME',
        compatible_controller: ['nintendoswitch_pro_controller'],
        image_url: 'https://fs-prod-cdn.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_MetalSlug1stAnd2ndMissionDoublePack_image500w.jpg',
        originally_for_t: 'HAC',
        cloud_saves_b: true,
        priority: '2031-09-15T15:00:00Z',
        digital_version_b: true,
        title_extras_txt: ['"METAL SLUG 1st & 2nd MISSION" Double Pack'],
        image_url_h2x1_s: 'https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_download_software_1/H2x1_NSwitchDS_MetalSlug1stAnd2ndMissionDoublePack_image500w.jpg',
        system_type: ['nintendoswitch_downloadsoftware'],
        age_rating_sorting_i: 12,
        game_categories_txt: ['action', 'shooter'],
        play_mode_tabletop_mode_b: true,
        publisher: 'SNK',
        product_code_ss: ['HACPAZPWA'],
        excerpt: 'From the hit action series METAL SLUG comes two popular titles on the NGPC for you to enjoy! Jump into battle and complete all the missions!',
        nsuid_txt: ['70010000034009'],
        date_from: '2021-09-15T00:00:00Z',
        language_availability: ['english,japanese'],
        price_has_discount_b: false,
        product_catalog_description_s: 'From the hit action series METAL SLUG comes two popular titles on the NGPC for you to enjoy! Jump into battle and complete all the missions!',
        price_discount_percentage_f: 0,
        title: '"METAL SLUG 1st & 2nd MISSION" Double Pack',
        sorting_title: '"METAL SLUG 1st & 2nd MISSION" Double Pack',
        copyright_s: '©SNK CORPORATION ALL RIGHTS RESERVED.',
        wishlist_email_square_image_url_s: 'https://fs-prod-cdn.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_MetalSlug1stAnd2ndMissionDoublePack_square_image_wishlist.jpg',
        players_to: 1,
        wishlist_email_banner640w_image_url_s: 'https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_download_software_1/H2x1_NSwitchDS_MetalSlug1stAnd2ndMissionDoublePack_banner_image_wishlist_640w.jpg',
        playable_on_txt: ['HAC'],
        hits_i: 300,
        pretty_game_categories_txt: ['Action', 'Shooter'],
        switch_game_voucher_b: false,
        game_category: ['action,shooter'],
        system_names_txt: ['Nintendo Switch'],
        pretty_agerating_s: 'PEGI 12',
        price_regular_f: 13.49,
        eshop_removed_b: false,
        age_rating_type: 'pegi',
        price_sorting_f: 13.49,
        price_lowest_f: 13.49,
        age_rating_value: '12',
        physical_version_b: false,
        wishlist_email_banner460w_image_url_s: 'https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_download_software_1/H2x1_NSwitchDS_MetalSlug1stAnd2ndMissionDoublePack_banner_image_wishlist_460w.jpg',
        _version_: 1735624225142603800
    }

    static jpGameData = {
        InitialCode: "HACAACAA",
        TitleName: "魔界戦記ディスガイア5",
        MakerName: "日本一ソフトウェア",
        MakerKana: "",
        Price: "7, 538円(税込)",
        SalesDate: "2017.3.3",
        SoftType: "pkg_dl",
        PlatformID: 2002,
        DlIconFlg: 1,
        LinkURL: "/titles/70010000000148",
        ScreenshotImgFlg: 1,
        ScreenshotImgURL: "https://img-eshop.cdn.nintendo.net/i/1c34e431fa5d1b1198515e22e1beafe45b9050b5b5b28403f15cd315af0944f7.jpg"
    }

    static priceDataSample = {
        title_id: 70070000011030,
        sales_status: 'onsale',
        regular_price: { amount: 'R1,129.00', currency: 'ZAR', raw_value: '1129' },
        gold_point: {
            basic_gift_gp: '565',
            basic_gift_rate: '0.05',
            consume_gp: '0',
            extra_gold_points: [],
            gift_gp: '565',
            gift_rate: '0.05'
        },
        region: 'ZA'
    }

    static modifiedPriceData = {
        priceInUsd: '2682.0',
        isDiscount: false,
        countyEmoji: '🇿🇦',
        regularPrice: 'R450.00',
        localCurency: 'ZAR',
        discountPrice: null,
        discountEndDate: null,
        salePercent: null,
        id: 70010000033132
    }
}